// This file centralizes the definition of all available tools, organized by category.
export const categories = [
  {
    name: 'Popular Tools',
    nameKey: 'toolCategory.popularTools',
    tools: [
      {
        href: import.meta.env.BASE_URL + 'src/pages/pdf-multi-tool.html',
        name: 'PDF Multi Tool',
        nameKey: 'tool.pdfMultiTool',
        icon: 'pencil-ruler',
        subtitle: 'Merge, Split, Organize, Delete, Rotate, Add Blank Pages, Extract and Duplicate in an unified interface.',
        subtitleKey: 'tool.pdfMultiTool.desc',
      },
      {
        href: import.meta.env.BASE_URL + 'src/pages/merge-pdf.html',
        name: 'Merge PDF',
        nameKey: 'tool.mergePDF',
        icon: 'combine',
        subtitle: 'Combine multiple PDFs into one file. Preserves Bookmarks.',
        subtitleKey: 'tool.mergePDF.desc',
      },
      {
        href: import.meta.env.BASE_URL + 'src/pages/split-pdf.html',
        name: 'Split PDF',
        nameKey: 'tool.splitPDF',
        icon: 'scissors',
        subtitle: 'Extract a range of pages into a new PDF.',
        subtitleKey: 'tool.splitPDF.desc',
      },
      {
        href: import.meta.env.BASE_URL + 'src/pages/compress-pdf.html',
        name: 'Compress PDF',
        nameKey: 'tool.compressPDF',
        icon: 'zap',
        subtitle: 'Reduce the file size of your PDF.',
        subtitleKey: 'tool.compressPDF.desc',
      },
      {
        href: import.meta.env.BASE_URL + 'src/pages/edit-pdf.html',
        name: 'PDF Editor',
        nameKey: 'tool.pdfEditor',
        icon: 'pocket-knife',
        subtitle:
          'Annotate, highlight, redact, comment, add shapes/images, search, and view PDFs',
        subtitleKey: 'tool.pdfEditor.desc',
      },
      {
        href: import.meta.env.BASE_URL + 'src/pages/jpg-to-pdf.html',
        name: 'JPG to PDF',
        nameKey: 'tool.jpgToPDF',
        icon: 'image-up',
        subtitle: 'Create a PDF from one or more JPG images.',
        subtitleKey: 'tool.jpgToPDF.desc',
      },
      {
        id: 'sign-pdf',
        name: 'Sign PDF',
        nameKey: 'tool.signPDF',
        icon: 'pen-tool',
        subtitle: 'Draw, type, or upload your signature.',
        subtitleKey: 'tool.signPDF.desc',
      },
      {
        id: 'cropper',
        name: 'Crop PDF',
        nameKey: 'tool.cropPDF',
        icon: 'crop',
        subtitle: 'Trim the margins of every page in your PDF.',
        subtitleKey: 'tool.cropPDF.desc',
      },
      {
        id: 'extract-pages',
        name: 'Extract Pages',
        nameKey: 'tool.extractPages',
        icon: 'ungroup',
        subtitle: 'Save a selection of pages as new files.',
        subtitleKey: 'tool.extractPages.desc',
      },
      {
        id: 'duplicate-organize',
        name: 'Duplicate & Organize',
        nameKey: 'tool.duplicateOrganize',
        icon: 'files',
        subtitle: 'Duplicate, reorder, and delete pages.',
        subtitleKey: 'tool.duplicateOrganize.desc',
      },
      {
        id: 'delete-pages',
        name: 'Delete Pages',
        nameKey: 'tool.deletePages',
        icon: 'trash-2',
        subtitle: 'Remove specific pages from your document.',
        subtitleKey: 'tool.deletePages.desc',
      },
    ],
  },
  {
    name: 'Edit & Annotate',
    nameKey: 'toolCategory.editAnnotate',
    tools: [
      {
        href: import.meta.env.BASE_URL + 'src/pages/edit-pdf.html',
        name: 'PDF Editor',
        nameKey: 'tool.pdfEditor',
        icon: 'pocket-knife',
        subtitle:
          'Annotate, highlight, redact, comment, add shapes/images, search, and view PDFs.',
        subtitleKey: 'tool.pdfEditor.desc',
      },
      {
        // id: 'bookmark-pdf',
        href: import.meta.env.BASE_URL + 'src/pages/bookmark.html',
        name: 'Edit Bookmarks',
        nameKey: 'tool.editBookmarks',
        icon: 'bookmark',
        subtitle: 'Add, edit, import, delete and extract PDF bookmarks.',
        subtitleKey: 'tool.editBookmarks.desc',
      },
      {
        href: import.meta.env.BASE_URL + 'src/pages/table-of-contents.html',
        name: 'Table of Contents',
        nameKey: 'tool.tableOfContents',
        icon: 'list',
        subtitle: 'Generate a table of contents page from PDF bookmarks.',
        subtitleKey: 'tool.tableOfContents.desc',
      },
      {
        id: 'add-page-numbers',
        name: 'Page Numbers',
        nameKey: 'tool.pageNumbers',
        icon: 'list-ordered',
        subtitle: 'Insert page numbers into your document.',
        subtitleKey: 'tool.pageNumbers.desc',
      },
      {
        id: 'add-watermark',
        name: 'Add Watermark',
        nameKey: 'tool.addWatermark',
        icon: 'droplets',
        subtitle: 'Stamp text or an image over your PDF pages.',
        subtitleKey: 'tool.addWatermark.desc',
      },
      {
        id: 'add-header-footer',
        name: 'Header & Footer',
        nameKey: 'tool.headerFooter',
        icon: 'pilcrow',
        subtitle: 'Add text to the top and bottom of pages.',
        subtitleKey: 'tool.headerFooter.desc',
      },
      {
        id: 'invert-colors',
        name: 'Invert Colors',
        nameKey: 'tool.invertColors',
        icon: 'contrast',
        subtitle: 'Create a "dark mode" version of your PDF.',
        subtitleKey: 'tool.invertColors.desc',
      },
      {
        id: 'change-background-color',
        name: 'Background Color',
        nameKey: 'tool.backgroundColor',
        icon: 'palette',
        subtitle: 'Change the background color of your PDF.',
        subtitleKey: 'tool.backgroundColor.desc',
      },
      {
        id: 'change-text-color',
        name: 'Change Text Color',
        nameKey: 'tool.changeTextColor',
        icon: 'type',
        subtitle: 'Change the color of text in your PDF.',
        subtitleKey: 'tool.changeTextColor.desc',
      },
      {
        id: 'sign-pdf',
        name: 'Sign PDF',
        nameKey: 'tool.signPDF',
        icon: 'pen-tool',
        subtitle: 'Draw, type, or upload your signature.',
        subtitleKey: 'tool.signPDF.desc',
      },
      {
        href: import.meta.env.BASE_URL + 'src/pages/add-stamps.html',
        name: 'Add Stamps',
        nameKey: 'tool.addStamps',
        icon: 'stamp',
        subtitle: 'Add image stamps to your PDF using the annotation toolbar.',
        subtitleKey: 'tool.addStamps.desc',
      },
      {
        id: 'remove-annotations',
        name: 'Remove Annotations',
        nameKey: 'tool.removeAnnotations',
        icon: 'eraser',
        subtitle: 'Strip comments, highlights, and links.',
        subtitleKey: 'tool.removeAnnotations.desc',
      },
      {
        id: 'cropper',
        name: 'Crop PDF',
        nameKey: 'tool.cropPDF',
        icon: 'crop',
        subtitle: 'Trim the margins of every page in your PDF.',
        subtitleKey: 'tool.cropPDF.desc',
      },
      {
        id: 'form-filler',
        name: 'PDF Form Filler',
        nameKey: 'tool.pdfFormFiller',
        icon: 'square-pen',
        subtitle: 'Fill in forms directly in the browser. Also supports XFA forms.',
        subtitleKey: 'tool.pdfFormFiller.desc',
      },
      {
        href: import.meta.env.BASE_URL + 'src/pages/form-creator.html',
        name: 'Create PDF Form',
        nameKey: 'tool.createPDFForm',
        icon: 'file-input',
        subtitle: 'Create fillable PDF forms with drag-and-drop text fields.',
        subtitleKey: 'tool.createPDFForm.desc',
      },
      {
        id: 'remove-blank-pages',
        name: 'Remove Blank Pages',
        nameKey: 'tool.removeBlankPages',
        icon: 'file-minus-2',
        subtitle: 'Automatically detect and delete blank pages.',
        subtitleKey: 'tool.removeBlankPages.desc',
      },
    ],
  },
  {
    name: 'Convert to PDF',
    nameKey: 'toolCategory.convertToPDF',
    tools: [
      {
        id: 'image-to-pdf',
        name: 'Image to PDF',
        nameKey: 'tool.imageToPDF',
        icon: 'images',
        subtitle: 'Convert JPG, PNG, WebP, BMP, TIFF, SVG, HEIC to PDF.',
        subtitleKey: 'tool.imageToPDF.desc',
      },
      {
        href: import.meta.env.BASE_URL + 'src/pages/jpg-to-pdf.html',
        name: 'JPG to PDF',
        nameKey: 'tool.jpgToPDF',
        icon: 'image-up',
        subtitle: 'Create a PDF from one or more JPG images.',
        subtitleKey: 'tool.jpgToPDF.desc',
      },
      {
        id: 'png-to-pdf',
        name: 'PNG to PDF',
        nameKey: 'tool.pngToPDF',
        icon: 'image-up',
        subtitle: 'Create a PDF from one or more PNG images.',
        subtitleKey: 'tool.pngToPDF.desc',
      },
      {
        id: 'webp-to-pdf',
        name: 'WebP to PDF',
        nameKey: 'tool.webpToPDF',
        icon: 'image-up',
        subtitle: 'Create a PDF from one or more WebP images.',
        subtitleKey: 'tool.webpToPDF.desc',
      },
      {
        id: 'svg-to-pdf',
        name: 'SVG to PDF',
        nameKey: 'tool.svgToPDF',
        icon: 'pen-tool',
        subtitle: 'Create a PDF from one or more SVG images.',
        subtitleKey: 'tool.svgToPDF.desc',
      },
      {
        id: 'bmp-to-pdf',
        name: 'BMP to PDF',
        nameKey: 'tool.bmpToPDF',
        icon: 'image',
        subtitle: 'Create a PDF from one or more BMP images.',
        subtitleKey: 'tool.bmpToPDF.desc',
      },
      {
        id: 'heic-to-pdf',
        name: 'HEIC to PDF',
        nameKey: 'tool.heicToPDF',
        icon: 'smartphone',
        subtitle: 'Create a PDF from one or more HEIC images.',
        subtitleKey: 'tool.heicToPDF.desc',
      },
      {
        id: 'tiff-to-pdf',
        name: 'TIFF to PDF',
        nameKey: 'tool.tiffToPDF',
        icon: 'layers',
        subtitle: 'Create a PDF from one or more TIFF images.',
        subtitleKey: 'tool.tiffToPDF.desc',
      },
      {
        id: 'txt-to-pdf',
        name: 'Text to PDF',
        nameKey: 'tool.textToPDF',
        icon: 'file-pen',
        subtitle: 'Convert a plain text file into a PDF.',
        subtitleKey: 'tool.textToPDF.desc',
      },
      {
        href: import.meta.env.BASE_URL + 'src/pages/json-to-pdf.html',
        name: 'JSON to PDF',
        nameKey: 'tool.jsonToPDF',
        icon: 'file-code',
        subtitle: 'Convert JSON files to PDF format.',
        subtitleKey: 'tool.jsonToPDF.desc',
      },
      // { id: 'md-to-pdf', name: 'Markdown to PDF', icon: 'file-text', subtitle: 'Convert a Markdown file into a PDF.' },
      // { id: 'scan-to-pdf', name: 'Scan to PDF', icon: 'camera', subtitle: 'Use your camera to create a scanned PDF.' },
      // { id: 'word-to-pdf', name: 'Word to PDF', icon: 'file-text', subtitle: 'Convert .docx documents to PDF.' },
    ],
  },
  {
    name: 'Convert from PDF',
    nameKey: 'toolCategory.convertFromPDF',
    tools: [
      {
        id: 'pdf-to-jpg',
        name: 'PDF to JPG',
        nameKey: 'tool.pdfToJPG',
        icon: 'file-image',
        subtitle: 'Convert each PDF page into a JPG image.',
        subtitleKey: 'tool.pdfToJPG.desc',
      },
      {
        id: 'pdf-to-png',
        name: 'PDF to PNG',
        nameKey: 'tool.pdfToPNG',
        icon: 'file-image',
        subtitle: 'Convert each PDF page into a PNG image.',
        subtitleKey: 'tool.pdfToPNG.desc',
      },
      {
        id: 'pdf-to-webp',
        name: 'PDF to WebP',
        nameKey: 'tool.pdfToWebP',
        icon: 'file-image',
        subtitle: 'Convert each PDF page into a WebP image.',
        subtitleKey: 'tool.pdfToWebP.desc',
      },
      {
        id: 'pdf-to-bmp',
        name: 'PDF to BMP',
        nameKey: 'tool.pdfToBMP',
        icon: 'file-image',
        subtitle: 'Convert each PDF page into a BMP image.',
        subtitleKey: 'tool.pdfToBMP.desc',
      },
      {
        id: 'pdf-to-tiff',
        name: 'PDF to TIFF',
        nameKey: 'tool.pdfToTIFF',
        icon: 'file-image',
        subtitle: 'Convert each PDF page into a TIFF image.',
        subtitleKey: 'tool.pdfToTIFF.desc',
      },
      {
        id: 'pdf-to-greyscale',
        name: 'PDF to Greyscale',
        nameKey: 'tool.pdfToGreyscale',
        icon: 'palette',
        subtitle: 'Convert all colors to black and white.',
        subtitleKey: 'tool.pdfToGreyscale.desc',
      },
      {
        href: import.meta.env.BASE_URL + 'src/pages/pdf-to-json.html',
        name: 'PDF to JSON',
        nameKey: 'tool.pdfToJSON',
        icon: 'file-code',
        subtitle: 'Convert PDF files to JSON format.',
        subtitleKey: 'tool.pdfToJSON.desc',
      },
      // { id: 'pdf-to-markdown', name: 'PDF to Markdown', icon: 'file-pen', subtitle: 'Extract text into a Markdown file.' },
    ],
  },
  {
    name: 'Organize & Manage',
    nameKey: 'toolCategory.organizeManage',
    tools: [
      {
        id: 'ocr-pdf',
        name: 'OCR PDF',
        nameKey: 'tool.ocrPDF',
        icon: 'scan-text',
        subtitle: 'Make a PDF searchable and copyable.',
        subtitleKey: 'tool.ocrPDF.desc',
      },
      {
        href: import.meta.env.BASE_URL + 'src/pages/merge-pdf.html',
        name: 'Merge PDF',
        nameKey: 'tool.mergePDF',
        icon: 'combine',
        subtitle: 'Combine multiple PDFs into one file.',
        subtitleKey: 'tool.mergePDF.desc',
      },
      {
        id: 'alternate-merge',
        name: 'Alternate & Mix Pages',
        nameKey: 'tool.alternateMerge',
        icon: 'shuffle',
        subtitle: 'Merge PDFs by alternating pages from each PDF. Preserves Bookmarks',
        subtitleKey: 'tool.alternateMerge.desc',
      },
      {
        id: 'organize',
        name: 'Organize PDF',
        nameKey: 'tool.organizePDF',
        icon: 'grip',
        subtitle: 'Reorder pages by dragging and dropping.',
        subtitleKey: 'tool.organizePDF.desc',
      },
      {
        id: 'duplicate-organize',
        name: 'Duplicate & Organize',
        nameKey: 'tool.duplicateOrganize',
        icon: 'files',
        subtitle: 'Duplicate, reorder, and delete pages.',
        subtitleKey: 'tool.duplicateOrganize.desc',
      },
      {
        id: 'add-attachments',
        name: 'Add Attachments',
        nameKey: 'tool.addAttachments',
        icon: 'paperclip',
        subtitle: 'Embed one or more files into your PDF.',
        subtitleKey: 'tool.addAttachments.desc',
      },
      {
        id: 'extract-attachments',
        name: 'Extract Attachments',
        nameKey: 'tool.extractAttachments',
        icon: 'download',
        subtitle: 'Extract all embedded files from PDF(s) as a ZIP.',
        subtitleKey: 'tool.extractAttachments.desc',
      },
      {
        id: 'edit-attachments',
        name: 'Edit Attachments',
        nameKey: 'tool.editAttachments',
        icon: 'file-edit',
        subtitle: 'View or remove attachments in your PDF.',
        subtitleKey: 'tool.editAttachments.desc',
      },
      {
        href: import.meta.env.BASE_URL + 'src/pages/pdf-multi-tool.html',
        name: 'PDF Multi Tool',
        nameKey: 'tool.pdfMultiTool',
        icon: 'pencil-ruler',
        subtitle: 'Full-featured PDF editor with page management.',
        subtitleKey: 'tool.pdfMultiTool.desc',
      },
      {
        id: 'split',
        name: 'Split PDF',
        nameKey: 'tool.splitPDF',
        icon: 'scissors',
        subtitle: 'Extract a range of pages into a new PDF.',
        subtitleKey: 'tool.splitPDF.desc',
      },
      {
        id: 'split-in-half',
        name: 'Divide Pages',
        nameKey: 'tool.splitInHalf',
        icon: 'table-columns-split',
        subtitle: 'Divide pages horizontally or vertically.',
        subtitleKey: 'tool.splitInHalf.desc',
      },
      {
        id: 'extract-pages',
        name: 'Extract Pages',
        nameKey: 'tool.extractPages',
        icon: 'ungroup',
        subtitle: 'Save a selection of pages as new files.',
        subtitleKey: 'tool.extractPages.desc',
      },
      {
        id: 'delete-pages',
        name: 'Delete Pages',
        nameKey: 'tool.deletePages',
        icon: 'trash-2',
        subtitle: 'Remove specific pages from your document.',
        subtitleKey: 'tool.deletePages.desc',
      },
      {
        id: 'add-blank-page',
        name: 'Add Blank Page',
        nameKey: 'tool.addBlankPage',
        icon: 'file-plus-2',
        subtitle: 'Insert an empty page anywhere in your PDF.',
        subtitleKey: 'tool.addBlankPage.desc',
      },
      {
        id: 'reverse-pages',
        name: 'Reverse Pages',
        nameKey: 'tool.reversePages',
        icon: 'arrow-down-z-a',
        subtitle: 'Flip the order of all pages in your document.',
        subtitleKey: 'tool.reversePages.desc',
      },
      {
        id: 'rotate',
        name: 'Rotate PDF',
        nameKey: 'tool.rotatePDF',
        icon: 'rotate-cw',
        subtitle: 'Turn pages in 90-degree increments.',
        subtitleKey: 'tool.rotatePDF.desc',
      },
      {
        id: 'n-up',
        name: 'N-Up PDF',
        nameKey: 'tool.nUpPDF',
        icon: 'layout-grid',
        subtitle: 'Arrange multiple pages onto a single sheet.',
        subtitleKey: 'tool.nUpPDF.desc',
      },
      {
        id: 'combine-single-page',
        name: 'Combine to Single Page',
        nameKey: 'tool.combineToSinglePage',
        icon: 'unfold-vertical',
        subtitle: 'Stitch all pages into one continuous scroll.',
        subtitleKey: 'tool.combineToSinglePage.desc',
      },
      {
        id: 'view-metadata',
        name: 'View Metadata',
        nameKey: 'tool.viewMetadata',
        icon: 'info',
        subtitle: 'Inspect the hidden properties of your PDF.',
        subtitleKey: 'tool.viewMetadata.desc',
      },
      {
        id: 'edit-metadata',
        name: 'Edit Metadata',
        nameKey: 'tool.editMetadata',
        icon: 'file-cog',
        subtitle: 'Change the author, title, and other properties.',
        subtitleKey: 'tool.editMetadata.desc',
      },
      {
        id: 'pdf-to-zip',
        name: 'PDFs to ZIP',
        nameKey: 'tool.pdfToZIP',
        icon: 'stretch-horizontal',
        subtitle: 'Package multiple PDF files into a ZIP archive.',
        subtitleKey: 'tool.pdfToZIP.desc',
      },
      {
        id: 'compare-pdfs',
        name: 'Compare PDFs',
        nameKey: 'tool.comparePDFs',
        icon: 'git-compare',
        subtitle: 'Compare two PDFs side by side.',
        subtitleKey: 'tool.comparePDFs.desc',
      },
      {
        id: 'posterize',
        name: 'Posterize PDF',
        nameKey: 'tool.posterizePDF',
        icon: 'notepad-text-dashed',
        subtitle: 'Split a large page into multiple smaller pages.',
        subtitleKey: 'tool.posterizePDF.desc',
      },
    ],
  },
  {
    name: 'Optimize & Repair',
    nameKey: 'toolCategory.optimizeRepair',
    tools: [
      {
        href: import.meta.env.BASE_URL + 'src/pages/compress-pdf.html',
        name: 'Compress PDF',
        nameKey: 'tool.compressPDF',
        icon: 'zap',
        subtitle: 'Reduce the file size of your PDF.',
        subtitleKey: 'tool.compressPDF.desc',
      },
      {
        id: 'fix-dimensions',
        name: 'Fix Page Size',
        nameKey: 'tool.fixPageSize',
        icon: 'ruler-dimension-line',
        subtitle: 'Standardize all pages to a uniform size.',
        subtitleKey: 'tool.fixPageSize.desc',
      },
      {
        id: 'linearize',
        name: 'Linearize PDF',
        nameKey: 'tool.linearizePDF',
        icon: 'gauge',
        subtitle: 'Optimize PDF for fast web viewing.',
        subtitleKey: 'tool.linearizePDF.desc',
      },
      {
        id: 'page-dimensions',
        name: 'Page Dimensions',
        nameKey: 'tool.pageDimensions',
        icon: 'ruler',
        subtitle: 'Analyze page size, orientation, and units.',
        subtitleKey: 'tool.pageDimensions.desc',
      },
      {
        id: 'remove-restrictions',
        name: 'Remove Restrictions',
        nameKey: 'tool.removeRestrictions',
        icon: 'unlink',
        subtitle:
          'Remove password protection and security restrictions associated with digitally signed PDF files.',
        subtitleKey: 'tool.removeRestrictions.desc',
      },
      {
        href: import.meta.env.BASE_URL + 'src/pages/repair-pdf.html',
        name: 'Repair PDF',
        nameKey: 'tool.repairPDF',
        icon: 'wrench',
        subtitle: 'Recover data from corrupted or damaged PDF files.',
        subtitleKey: 'tool.repairPDF.desc',
      },
    ],
  },
  {
    name: 'Secure PDF',
    nameKey: 'toolCategory.securePDF',
    tools: [
      {
        id: 'encrypt',
        name: 'Encrypt PDF',
        nameKey: 'tool.encryptPDF',
        icon: 'lock',
        subtitle: 'Lock your PDF by adding a password.',
        subtitleKey: 'tool.encryptPDF.desc',
      },
      {
        id: 'sanitize-pdf',
        name: 'Sanitize PDF',
        nameKey: 'tool.sanitizePDF',
        icon: 'brush-cleaning',
        subtitle: 'Remove metadata, annotations, scripts, and more.',
        subtitleKey: 'tool.sanitizePDF.desc',
      },
      {
        id: 'decrypt',
        name: 'Decrypt PDF',
        nameKey: 'tool.decryptPDF',
        icon: 'unlock',
        subtitle: 'Unlock PDF by removing password protection.',
        subtitleKey: 'tool.decryptPDF.desc',
      },
      {
        id: 'flatten',
        name: 'Flatten PDF',
        nameKey: 'tool.flattenPDF',
        icon: 'layers',
        subtitle: 'Make form fields and annotations non-editable.',
        subtitleKey: 'tool.flattenPDF.desc',
      },
      {
        id: 'remove-metadata',
        name: 'Remove Metadata',
        nameKey: 'tool.removeMetadata',
        icon: 'file-x',
        subtitle: 'Strip hidden data from your PDF.',
        subtitleKey: 'tool.removeMetadata.desc',
      },
      {
        id: 'change-permissions',
        name: 'Change Permissions',
        nameKey: 'tool.changePermissions',
        icon: 'shield-check',
        subtitle: 'Set or change user permissions on a PDF.',
        subtitleKey: 'tool.changePermissions.desc',
      },
    ],
  },
];
